import type { GlyphStroke } from './fontParser'
import type { PathCommand } from 'opentype.js'

export interface PrintSettings {
  bedWidth: number       // mm
  bedHeight: number      // mm
  penDownZ: number       // mm — where pen touches paper
  penUpZ: number         // mm — clearance height
  writeSpeed: number     // mm/min
  travelSpeed: number    // mm/min
  previewWidth: number   // px — canvas width for SVG preview
  previewHeight: number  // px — canvas height for SVG preview
}

export const DEFAULT_SETTINGS: PrintSettings = {
  bedWidth: 250,
  bedHeight: 210,
  penDownZ: 0,
  penUpZ: 5,
  writeSpeed: 1500,
  travelSpeed: 3000,
  previewWidth: 700,
  previewHeight: 590,
}

export function generateGCode(strokes: GlyphStroke[][], settings: PrintSettings): string {
  const { penDownZ, penUpZ, writeSpeed, travelSpeed } = settings
  const lines: string[] = []

  lines.push('; Generated by 3D Writer')
  lines.push('; -------------------------')
  lines.push('G21 ; mm mode')
  lines.push('G90 ; absolute positioning')
  lines.push('G28 X Y ; home XY')
  lines.push(`G0 Z${penUpZ} F${travelSpeed} ; pen up`)
  lines.push('')

  for (const glyphStrokes of strokes) {
    for (const stroke of glyphStrokes) {
      let penDown = false

      for (const cmd of stroke.commands) {
        switch (cmd.type) {
          case 'M': {
            if (penDown) {
              lines.push(`G0 Z${penUpZ} F${travelSpeed}`)
              penDown = false
            }
            lines.push(`G0 X${fmt(cmd.x)} Y${fmt(cmd.y)} F${travelSpeed}`)
            lines.push(`G0 Z${penDownZ} F${travelSpeed}`)
            penDown = true
            break
          }
          case 'L': {
            lines.push(`G1 X${fmt(cmd.x)} Y${fmt(cmd.y)} F${writeSpeed}`)
            break
          }
          case 'C': {
            // Approximate cubic bezier with line segments
            const segs = bezierToLines(cmd)
            for (const [x, y] of segs) {
              lines.push(`G1 X${fmt(x)} Y${fmt(y)} F${writeSpeed}`)
            }
            break
          }
          case 'Q': {
            const segs = quadToLines(cmd)
            for (const [x, y] of segs) {
              lines.push(`G1 X${fmt(x)} Y${fmt(y)} F${writeSpeed}`)
            }
            break
          }
          case 'Z': {
            if (penDown) {
              lines.push(`G0 Z${penUpZ} F${travelSpeed}`)
              penDown = false
            }
            break
          }
        }
      }

      if (penDown) {
        lines.push(`G0 Z${penUpZ} F${travelSpeed}`)
      }
    }
  }

  lines.push('')
  lines.push('; Done')
  lines.push('G28 X Y ; home XY')
  lines.push(`G0 Z${penUpZ + 10} F${travelSpeed} ; raise pen`)

  return lines.join('\n')
}

function fmt(n: number): string {
  return n.toFixed(3)
}

function bezierToLines(cmd: Extract<PathCommand, { type: 'C' }>, steps = 20): [number, number][] {
  // We need the start point, but opentype gives us absolute coords for the control/end points.
  // Since we don't have the prior point here, we sample relative to the endpoint.
  const result: [number, number][] = []
  const { x1, y1, x2, y2, x, y } = cmd
  // Assume start ~ x1 (rough — proper impl would track current pos)
  const x0 = x1
  const y0 = y1
  for (let i = 1; i <= steps; i++) {
    const t = i / steps
    const bx = (1-t)**3*x0 + 3*(1-t)**2*t*x1 + 3*(1-t)*t**2*x2 + t**3*x
    const by = (1-t)**3*y0 + 3*(1-t)**2*t*y1 + 3*(1-t)*t**2*y2 + t**3*y
    result.push([bx, by])
  }
  return result
}

function quadToLines(cmd: Extract<PathCommand, { type: 'Q' }>, steps = 15): [number, number][] {
  const result: [number, number][] = []
  const { x1, y1, x, y } = cmd
  const x0 = x1
  const y0 = y1
  for (let i = 1; i <= steps; i++) {
    const t = i / steps
    const bx = (1-t)**2*x0 + 2*(1-t)*t*x1 + t**2*x
    const by = (1-t)**2*y0 + 2*(1-t)*t*y1 + t**2*y
    result.push([bx, by])
  }
  return result
}
